src/controllers/dependencies-diagram.ts, src/gen-ai-controllers/business-summary.ts
dependency diagram and entities changes
=> dependency diagram and entities changes

src/config/db/init-db-genAi-json, src/config/db/init-db.json
changes in init-db.json and added init-db-genAi.json
=> changes in init-db.json and added init-db-genAi.json

sonar-project.properties, src/config/db/gen-ai-db.json, src/controllers/project-master.ts
=> release-22.03.2025

src/controllers/dependencies-diagram.ts, src/models/nodes-and-links.ts
changes for adding summary in dependency diagram
=> changes for adding summary in dependency diagram

src/config/db/gen-ai-db.json, src/server-app.ts
Update prompts in gen-ai-db.json and clean up server-app.ts
=> Update prompts in gen-ai-db.json and clean up server-app.ts

src/controllers/file-master.ts
=> added inventory api

src/controllers/dependencies-diagram.ts, src/controllers/project-master.ts, src/gen-ai-controllers/business-summary.ts
changes for handling entityName as None
=> changes for handling entityName as None

src/config/db/gen-ai-db.json
update prompt value in gen-ai-db.json for pseudo code
=> update prompt value in gen-ai-db.json for pseudo code

package.json, src/controllers/keyword-search.ts, src/express-app.ts
1. added-search-functionalities
=> added-search-functionalities

src/controllers/dashboard.ts, src/controllers/file-master.ts
=> dashboard changes

src/config/db/init-db.json, src/controllers/project-master.ts
changes for RPG in init-db.json
=> changes for RPG in init-db.json

src/config/db/gen-ai-db.json
update promptIds and add new i/o dataset prompts in gen-ai-db.json
=> update promptIds and add new i/o dataset prompts in gen-ai-db.json

src/gen-ai-controllers/business-rules.ts
Business rules graphml  changes
=> Business rules graphml  changes

src/controllers/dependencies-diagram.ts, src/gen-ai-controllers/business-summary.ts, src/models/nodes-and-links.ts
Added input output nodes to dependency diagram
=> Added input output nodes to dependency diagram

mongo-server.bat, src/config/db/gen-ai-db.json, src/controllers/dependencies-diagram.ts, src/controllers/user-master.ts
added api for change password screen and dependency diagram conflict resolved
=> added api for change password screen and dependency diagram conflict resolved

src/config/db/gen-ai-db.json, src/controllers/dependencies-diagram.ts
=> dependency diagram change

src/config/db/gen-ai-db.json, src/controllers/functional-flow.ts
=> functional flow changes

src/config/db/init-db.json, src/controllers/project-master.ts, src/models/nodes-and-links.ts
first-cut--dotnet--test-server--22052022
=> first-cut--dotnet--test-server--22052022

src/controllers/project-master.ts
changes for separate json for statement reference
=> changes for separate json for statement reference

src/controllers/functional-flow.ts
changes for functional navigator
=> changes for functional navigator

src/config/db/init-db.json
changes for Assembler in init-db json
=> changes for Assembler in init-db json

src/controllers/doc-master.ts, src/gen-ai-controllers/business-rules.ts
filecontent change and rules changes as per new utility
=> filecontent change and rules changes as per new utility

src/controllers/project-master.ts, src/controllers/user-master.ts, src/models/user-master.ts
changes for assigning projects in user management
=> changes for assigning projects to user

src/controllers/project-master.ts
changes in project master for assembler
=> changes in project master for assembler

mongo-server.bat, src/configurations.ts, src/express-app.ts
Added one new environment variables
BASE_ROUTER=backend
=> update MongoDB database path and use dynamic base router in express app

src/controllers/functional-flow.ts
Add asm file type for assembler
=> Add asm file type for assembler

src/controllers/project-master.ts, src/models/entity-master.ts, src/models/file-content-master.ts
changes for upload new project into existing workspace
- Uploaded new project into existing workspace
- Added project nodes into nodeDetails
- Added links for missing object.
- Updated call externals for missing objects
- Updated isMissing false after finding method for missing
=> changes for upload new project into existing workspace

src/controllers/dashboard.ts
changes in get systems and get Objects in gen ai menus
=> changes in get systems and get Objects in gen ai menus
